# Generated by Django 3.1.3 on 2021-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo_Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_capitulo', models.CharField(max_length=50)),
                ('temporada', models.IntegerField(default=0)),
                ('capitulo', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Series_Peliculas',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion_corta', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada_de_Serie',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion_corta', models.CharField(max_length=150)),
                ('nombre_temporada', models.CharField(max_length=50)),
                ('temporada_nro', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=1900)),
                ('cant_capitulos', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
