# Generated by Django 3.1.3 on 2021-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0002_capitulo_serie_pelicula_series_peliculas_temporada_de_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_peliculas',
            name='descripcion_corta',
            field=models.CharField(max_length=150),
        ),
    ]
